### ISSUE TITLE
minio does not start due to write permissions

### ISSUE THREAD

**Issue by ramonskie** [genesis-community/minio-genesis-kit#3]
```
ERROR Unable to configure one of server's RPC services: Unable to write to the b
      ackend.
      > Please ensure Minio binary has write permissions for the backend.
```

**Comment by ramonskie** [comment]
problem was related to disk size

**Comment by jhunt** [comment]
So it's just an unfortunate error message verbiage from minio, and not a problem with the kit?

**Comment by ramonskie** [comment]
yes it was.
maby a minimum disk-space check?

**Comment by jhunt** [comment]
Yes it was a bad error message or yes it was a problem with the kit?

We can advise on disk sizing, but I'm not sure that enforcing minimums is worth the effort.

**Comment by ramonskie** [comment]
yes it was just a bad error message.
i changed the disk_type to default which was 1G in my cloud-config.
maby this issue is enough for now if ppl have the same problems
