### ISSUE TITLE
Cert check in check script should check feature flags

### ISSUE THREAD

**Issue by krutten** [genesis-community/minio-genesis-kit#9]
If you select `self-signed` the kit will generate self signed certs with extra names like "*.minio.${params.network}.${params.env}-minio.bosh" the includes a check in the scripts to verify that domain exists

If you provide signed certificates, it most likely will not cover `*.bosh` domains which is not a valid TLD.  The check should be skipped if `provided-cert` is enabled.

**Comment by ramonskie** [comment]
can be closed as already fixed
